export const one = require('./one.png')
export const two = require('./two.png')
export const three = require('./three.png')

export const discoball = require('./rowslide/discoball.png')
export const dj = require('./rowslide/dj.png')
export const dock = require('./rowslide/dock.png')
export const gameboy = require('./rowslide/gameboy.png')
export const instruments = require('./rowslide/instruments.png')
export const kalei = require('./rowslide/kalei.png')
export const maracas = require('./rowslide/maracas.png')
export const synth = require('./rowslide/synth.png')
